### ISSUE TITLE
Fritzbox Tools (latest) broke RESTful switches / sensors (?)

### ISSUE THREAD

**Issue by agrimpelhuber** [mammuth/ha-fritzbox-tools#103]
On my HassOS-based RPi 3B installation of HA, one of the recent updates broke all RESTful switches and sensors. Even though CURL-based calls worked from within the HA container, the setup of those entities ended up in (please note: No DNS involved):

```
2020-06-25 08:02:59 ERROR (MainThread) [homeassistant.components.rest.switch] No route to resource/endpoint: http://192.168.178.168/switch.json
```

The async / aiohttp messages are not very specific at this point, but the most likely cause was a timeout of the relevant HTTP calls. Extending the timeout to more than 5 minutes didn't help, though. It's also remarkable that all switches did not work at all - not any of them.

After finding no solution, I ended up re-installing HA piece by piece on a new machine (RPi 3B+). Everything worked fine for a long time, until I installed HACS and the previously installed HACS-based integrations. That's when the RESTful communication broke again.

Removing and re-installing the integrations one by one, I ended up here: Whenever I re-install Fritzbox Tools, the RESTful switches stop working. No idea why. Here's one of my switch configurations. I know that it's a bit complicated, taking URL-encoded POST data and returning JSON, but it worked. However, even the most simple switch will be affected the same way.

```
switch:
  - platform: rest
    name: heating_override
    timeout: 20
    resource: 'http://192.168.178.202/switch.json'
    method: post
    body_on: 'state=on'
    body_off: 'state=off'
    is_on_template: '{{ value_json.logicstate }}'
    headers:
      Accept: text/json
      Content-Type: application/x-www-form-urlencoded
```
