### ISSUE TITLE
No Profile switch possible

### ISSUE THREAD

**Issue by MartinKuhl** [mammuth/ha-fritzbox-tools#105]
Hi I have installed this addon via HACS and than via Integration. If I do the configuration without listing indiviual devices everything went smoothed.
If I list individual defice for profile switching the setup wizzard do not create any entities in HA. 
If I do the old way via configuration.yaml I always get the message that home assisstand is starting an indivual services that's way are not ready.

Any ideas?

**Comment by mammuth** [comment]
Please take a log at your logs to identify potential issues. If there is nothing obvious in there, turn on debug logging:
```yaml
logger:
  default: warning
  logs:
    custom_components.fritzbox_tools: debug
```
