### ISSUE TITLE
Reboot not working

### ISSUE THREAD

**Issue by kersten-lohmeyer** [mammuth/ha-fritzbox-tools#161]
Hi,

HA version: core-2021.3.4
HACS version: 1.11.3
Fritzbox-Tools Addon version: 1.15.1

I have the integration setup, with my FRITZ!Box sitting at 192.168.1.1

I can switch on or off Wifi successfully via HA

When trying to reboot the FRITZ!Box with the following script:

```
fritz_box_reboot:
  alias: "Reboot FRITZ!Box"
  sequence:
  - service: fritzbox_tools.reboot
    data:
        host: 192.168.1.1
```

Then I always get the following error in the logfile:

`reboot: Please supply a valid hostname of a configured fritzbox for the service (e.g. 192.168.178.1)
0:20:17 – FRITZ!Box Tools (ERROR)`

And the box is NOT rebooting.

Any hints?

Thank you

**Comment by Hatzl** [comment]
Hi,

I have the same problem. Reboot and reconnect are both not working with the described error message.

FRITZ!Box: 6850
FRITZ-OS: 07.21

**Comment by kersten-lohmeyer** [comment]
FRITZ!Box 7583 in my case

**Comment by Bergerie** [comment]
Just installed via HACS, all functioning with the exception of reboot, reconfigure services. Running FRITZ!OS: 07.12 on Model 7560

**Comment by p1ranha** [comment]
Same here, 7560, FRITZ!OS: 07.12

**Comment by LuckyTriple7** [comment]
Same here, FritzBox7590, Repeater 600, Repeater 2400

reconnect: Please supply a valid hostname of a configured fritzbox for the service (e.g. 192.168.178.1)

**Comment by pooyashahidi** [comment]
the device is saved with it's config_entry as key:
`    hass.data[DOMAIN][DATA_FRITZ_TOOLS_INSTANCE][entry.entry_id] = fritz_tools
`so it makes no sense to use host as key when getting it:
`    fritztools = hass.data[DOMAIN][DATA_FRITZ_TOOLS_INSTANCE].get(host, None)
`
as a temporary workaround provide config_entry id as host when calling the service. For example:
```
        tap_action:
          action: call-service
          service: fritzbox_tools.reconnect
          service_data:
            host: 98a53f897d0c4ae89295f617f341cb7f
```
if you don't know the config entry id just click on "1 device" on your integration list below your router's name. The page url contains the config entry. It will look something like this:
.../config/integrations#config_entry=98a53f897d0c4ae89295f617f341cb7f
