### ISSUE TITLE
Pprofile and devices not working

### ISSUE THREAD

**Issue by naamah75** [mammuth/ha-fritzbox-tools#38]
`profile_on`, `profile_off `and `devices` is are considerate as invalid configuration for Home Assistant 0.102.0 and frtizbox-tool version 1.4.1.
The following is my configuration:
```
fritzbox:
  devices:
    - host: 192.168.1.1
      username: !secret fritzbox_username
      password: !secret fritzbox_password
      profile_on: "Standard"  
      profile_off: "Ospite"  
      devices: 
        - "HUAWEI-Mate-20-Pro-865641"
        - "HUAWEI-P20-4f29c9652c3aea"      
```
