### ISSUE TITLE
Unauthorized request trying to enable guest WiFi

### ISSUE THREAD

**Issue by TheLastProject** [mammuth/ha-fritzbox-tools#4]
I did make an account on my FritzBox and added it. Any way to debug what I'm doing wrong?

**Comment by mammuth** [comment]
Was that an exception or a logged debug message?

Try to turn the log level of the component to debug then it should print out the error message of the low level package that is used to communicate with the frtizbox (`fritzconnection`):

```
logger:
  default: warning
  logs:
    custom_components.fritzbox_tools: debug
```

If it's an exception (and no log message), it should already be coming from `fritzconnection`.
