### ISSUE TITLE
Device profile switch entities gone

### ISSUE THREAD

**Issue by Marvilius** [mammuth/ha-fritzbox-tools#44]
Hey there

Und I used your addon for 2 weeks now without a trouble.
Yesterday the switch entities for the profiles were gone, while guest wifi was still there as well as port forward...whats goin on and how can i fix that?

Thx

**Comment by AaronDavidSchneider** [comment]
Thankyou for the report.
Could you provide more details: Logs, Fritzbox version, etc.

Could you also double check if the names of your devices Match the ones found in your configuration.

**Comment by Marvilius** [comment]
I never specified any devicenames prior to now. I use a fb 6890 lte with actual 7.10 version of fritz os

**Comment by AaronDavidSchneider** [comment]
Since the release of 1.5, one needs to specify the monitored devices.
Just re-add the integration and specify the devices:

```
fritzbox_tools:
  host: "192.168.178.1"  # required
  username: "home-assistant"  # required (create one at `System > FRITZ!Box Benutzer` on your router)
  password: "yourfritzboxpassword"  # required
  homeassistant_ip: "192.168.178.42"  # Optional. Needed if you want to control port forwardings for the device running Home Assistant
  profile_on: "Standard"  # Optional. Needed if you want to switch between device profiles ("Zugangsprofile")
  profile_off: "Gesperrt"  # Optional. Needed if you want to switch between device profiles ("Zugangsprofile")
  devices: # Optional. If you don't want to expose a profile switch for just some of your network devices
    - "Helens-iPhone"
    - "Aarons-MacBook-Air"
    - "..."
```

You might need to remove the integration manually (see `Configuration` - `Integration`) before updating configuration.yaml. You can configure Fritzbox Tools right there since 1.5.
